
[general]
	#The alternative names of this material.
	alternativeNames = []
	#The byproducts of this material.
	extras = []
	#Is the storage block of this material small (2x2).
	isSmallStorageBlock = false
	#The module blacklist of this material.
	moduleBlacklist = []
	#Should items of this material have the enchanted glow.
	hasEffect = false
	#The model type of the material.
	modelType = "crystal"
	#The color of this material.
	color = 9873337

[molten]
	#The temperature of this molten fluid.
	temperature = 1000

[exnihilocreatio]
	#The default base to sieve in Ex Nihilo Creatio to get this material.
	oreBase = "#gravel"

[exnihilosequentia]
	#The output chance of the sieve recipes added using an iron mesh.
	sieveIronChance = 0.00800000037997961
	#The output chance of the sieve recipes added using a diamond mesh.
	sieveDiamondChance = 0.01600000075995922

[mekanism]
	#The default base to use in Mekanism's Combiner to recreate ores.
	oreBase = "minecraft:cobblestone"

